-- AlterTable
ALTER TABLE `lot` ADD COLUMN `installer_id` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `lot_tab` MODIFY `tab` ENUM('ARCHITECTURE_DRAWINGS', 'APPLIANCES_SPECIFICATIONS', 'MATERIAL_SELECTION', 'CABINETRY_DRAWINGS', 'CHANGES_TO_DO', 'SITE_MEASUREMENTS', 'DELIVERY_PHOTOS', 'INSTALLATION_PHOTOS', 'MAINTENANCE_PHOTOS', 'FINISHED_SITE_PHOTOS') NOT NULL;

-- AddForeignKey
ALTER TABLE `lot` ADD CONSTRAINT `lot_installer_id_fkey` FOREIGN KEY (`installer_id`) REFERENCES `employees`(`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;
