import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";

export const metadata = {
  title: "Privacy Policy | Ikonic Kitchens and Cabinets",
  description:
    "How Ikonic Kitchens and Cabinets collects, uses and protects personal information.",
};

const sections = [
  {
    title: "Information we collect",
    content: (
      <>
        <p>
          We collect personal information that you choose to provide when you
          contact us, request a quote or subscribe to our newsletter. This may
          include your name, email address, phone number, address, project
          details, messages and any images you choose to attach to an enquiry.
        </p>
        <p>
          We may also collect limited technical information generated by your
          use of this website, such as browser and device information, IP
          address, pages visited and information stored in your browser for
          website functionality.
        </p>
      </>
    ),
  },
  {
    title: "How we use your information",
    content: (
      <>
        <p>We use personal information to:</p>
        <ul>
          <li>respond to enquiries and arrange consultations;</li>
          <li>prepare quotes and provide our kitchen, cabinetry and related services;</li>
          <li>communicate about your project, account or requested information;</li>
          <li>send newsletters and marketing updates where you have subscribed;</li>
          <li>improve, secure and maintain our website and business operations; and</li>
          <li>meet legal, regulatory and record-keeping obligations.</li>
        </ul>
      </>
    ),
  },
  {
    title: "Newsletter, cookies and third-party services",
    content: (
      <>
        <p>
          Newsletter subscriptions are processed using EmailJS. When you
          subscribe, your email address is sent to that service so we can
          deliver the requested communications. You can opt out at any time by
          following the unsubscribe instructions in a marketing email or by
          contacting us.
        </p>
        <p>
          This website may use cookies, local storage and similar browser
          technologies to provide site features, remember session-related
          preferences in the authenticated administration area, and help keep
          the website secure. Our contact page includes a Google Maps embed,
          and our website links to social-media services. Those services may
          collect information under their own privacy policies when you view or
          follow their links.
        </p>
      </>
    ),
  },
  {
    title: "When we share information",
    content: (
      <p>
        We do not sell personal information. We may share it with trusted
        service providers who help us operate our website, communications or
        business services, or where disclosure is required or permitted by
        law. We only share information needed for the relevant purpose and
        expect providers to handle it appropriately.
      </p>
    ),
  },
  {
    title: "Storage, security and retention",
    content: (
      <p>
        We take reasonable steps to protect personal information from misuse,
        interference, loss and unauthorised access, modification or disclosure.
        No internet transmission or storage system is completely secure. We
        retain information only for as long as reasonably needed for the
        purposes described in this policy, our business records, or legal
        requirements.
      </p>
    ),
  },
  {
    title: "Access, correction and concerns",
    content: (
      <p>
        You may request access to, or correction of, personal information we
        hold about you, or raise a privacy concern, by emailing{" "}
        <a href="mailto:info@ikonickitchens.com.au">
          info@ikonickitchens.com.au
        </a>
        . We will respond within a reasonable time. This policy is intended to
        operate in accordance with applicable Australian privacy laws.
      </p>
    ),
  },
  {
    title: "Changes to this policy",
    content: (
      <p>
        We may update this Privacy Policy from time to time. The current
        version will always be published on this page, with its effective date.
      </p>
    ),
  },
];

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-linear-to-br from-slate-50 to-slate-100">
      <Navbar bar={true} />
      <main className="px-4 pb-16 pt-32 sm:px-6 lg:px-8">
        <article className="mx-auto max-w-4xl rounded-2xl bg-white p-6 shadow-xl sm:p-10 lg:p-12">
          <div className="mb-10 border-b border-slate-200 pb-8">
            <p className="mb-3 text-sm font-semibold uppercase tracking-wider text-[#B92F34]">
              Ikonic Kitchens and Cabinets
            </p>
            <h1 className="mb-4 text-4xl font-bold text-slate-900 sm:text-5xl">
              Privacy Policy
            </h1>
            <p className="text-slate-600">Effective date: 6 August 2026</p>
          </div>

          <div className="space-y-9 text-base leading-relaxed text-slate-700">
            <p>
              Ikonic Kitchens and Cabinets respects your privacy. This policy
              explains how we handle personal information collected through
              this website and when you contact us about our services.
            </p>

            {sections.map((section) => (
              <section key={section.title}>
                <h2 className="mb-3 text-2xl font-bold text-slate-900">
                  {section.title}
                </h2>
                <div className="space-y-4 [&_a]:font-medium [&_a]:text-[#B92F34] [&_a]:underline [&_a]:underline-offset-4 [&_li]:ml-5 [&_li]:list-disc [&_li]:pl-1">
                  {section.content}
                </div>
              </section>
            ))}

            <section>
              <h2 className="mb-3 text-2xl font-bold text-slate-900">Contact us</h2>
              <address className="not-italic">
                Ikonic Kitchens and Cabinets<br />
                5 Dundee Avenue, Holden Hill, South Australia 5088, Australia<br />
                <a href="mailto:info@ikonickitchens.com.au">
                  info@ikonickitchens.com.au
                </a>
              </address>
            </section>

            <p className="border-t border-slate-200 pt-6 text-sm text-slate-500">
              For the rules that apply to use of this website, please read our{" "}
              <Link href="/terms-of-service">Terms of Service</Link>.
            </p>
          </div>
        </article>
      </main>
      <Footer />
    </div>
  );
}
