-- AlterTable
ALTER TABLE `lot_tab` MODIFY `tab` ENUM('ARCHITECTURE_DRAWINGS', 'APPLIANCES_SPECIFICATIONS', 'MATERIAL_SELECTION', 'CABINETRY_DRAWINGS', 'CHANGES_TO_DO', 'SITE_MEASUREMENTS', 'DELIVERY_PHOTOS', 'INSTALLATION_PHOTOS', 'MAINTENANCE_PHOTOS') NOT NULL;
