export const fromData = {
  Kitchen: [
    "Overhead Cabinets",
    "LED Provision under overhead cabinets",
    "Underbench Drawers/Cabinets",
    "Tall Cupboards",
    "Oven / Microwave Tower",
    "Spice Rack",
    "Tall pull out pantry",
    "Integrated Fridge",
    "Integrated Microwave",
    "Integrated Dishwasher",
    "Benchtop",
    "Pull out bin with single basket",
    "Pull out bin with double baskets",
    "Extra drawer",
    "Ways to open drawers",
  ],
  "Kitchen Island": [
    "Underbench Drawers/Cabinets",
    "Back Panel",
    "One side water fall",
    "Both side water fall",
    "One side curve Island",
    "Both side curve Island",
    "Pull out bin with single basket",
    "Pull out bin with double baskets",
    "Integrated Dishwasher",
    "Benchtop",
  ],
  "Kitchen WIP": [
    "Overhead Cabinets",
    "Underbench Drawers/Cabinets",
    "Tall Cupboards",
    "Open Shelves",
    "Tall Pantry",
    "Pull out bin with single basket",
    "Pull out bin with double baskets",
    "Integrated dishwasher",
    "LED Provision under overhead cabinets",
  ],
  Laundry: [
    "Overhead Cabinets",
    "Underbench Drawers/Cabinets",
    "Tall Cupboards (BR)",
    "Hamper",
    "Ironboard Provision",
    "LED Provision under overhead cabinets",
    "Washer Tower",
    "Handles",
    "Knobs",
    "Finger Pull",
    "Push to Open",
    "Benchtop",
    "Space for robe walk",
  ],
  "Bath Vanity": [
    "Underbench Cabinets",
    "Extra drawer",
    "Handles",
    "Knobs",
    "Finger Pull",
    "Push to Open",
    "Wall Hung",
    "TOp Mount",
    "Under Mount",
    "LED Provision",
    "Open box",
    "Benchtop",
  ],
  "Powder Vanity": [
    "Underbench Cabinets",
    "Extra drawer",
    "Handles",
    "Knobs",
    "Finger Pull",
    "Push to Open",
    "Wall Hung",
    "TOp Mount",
    "Under Mount",
    "LED Provision",
    "Open box",
    "Benchtop",
  ],
  Bed: {
    Vanity: [
      "Underbench Cabinets",
      "Extra drawer",
      "Handles",
      "Knobs",
      "Finger Pull",
      "Push to Open",
      "Wall Hung",
      "Top Mount",
      "Under Mount",
      "LED Provision",
      "Open box",
      "Benchtop",
    ],
    option: {
      WIR: [
        "Drawer Tower, Open Shelves with Handging Rail",
        "Double hanging rail",
        "LED Provision",
        "Overhead Cabinets",
        "Handles",
        "Knobs",
        "Finger Pull",
        "Push to Open",
        "Dresser Space",
      ],
      BIR: ["Drawer Tower", "Hanging Rail", "Hinged Door"],
    },
  },
  "Linen Cupboard next to Study": ["Tall Cupboards"],
  Study: [
    "MDF Benchtop",
    "Drawer set",
    "Handles",
    "Knobs",
    "Finger Pull",
    "Push to Open",
    "Benchtop",
  ],
  "TV Unit in Theatre": [
    "Underbench Cabinets",
    "Benchtop",
    "Drawers",
    "Built in fire place",
    "Cading on wall",
    "Handles",
    "Knobs",
    "Finger Pull",
    "Push to Open",
    "Wall Hung",
    "Top Mount",
    "Under Mount",
    "LED Provision",
    "Open box",
  ],
  "Fire Place": ["Built in Fire place", "Wall claging"],
  "Bar or Wine Shleve": ["Underbench Door Cabinets"],
  "Alfresco (GF)": [
    "Overhead Cabinets",
    "Underbench Door Cabinets",
    "Benchtop",
    "BBQ Provision",
    "Weather Proof Material",
  ],
};
